
# The port that users will use to access the apps
restabuild.port=8080

# The working directory for storing git repos, building projects in etc
restabuild.data=target/local

# The number of builds that can run at the same time
restabuild.concurrent.builds=3

# The path to serve the website from or / to server from the root
restabuild.context=/restabuild

# The timeout threshold per run (unit in minute)
restabuild.timeout=30

# Controls whether to delete the instance directories of each build upon completion. Valid values: ALWAYS, NEVER, ON_SUCCESS
restabuild.delete.policy=ON_SUCCESS

# An optional regular expression pattern that git URLs must match. Empty to allow any URLs.
restabuild.git.url.pattern=https://github\.com/.*\.git

# The message to return to users if the git URL specified does not match the allowed regular expression
restabuild.git.url.validation.message=Only HTTPS github.com URLs are allowed

# The example URL to show in the UI
restabuild.example.url=https://github.com/3redronin/mu-server-sample.git